import LegalPage from './LegalPage';

const P = ({ children }) => <p className="legal-p">{children}</p>;
const UL = ({ items }) => <ul className="legal-ul">{items.map((item, i) => <li key={i}>{item}</li>)}</ul>;
const Warn = ({ children }) => <div className="legal-warn">{children}</div>;
const Table = ({ rows }) => (
  <div className="legal-table-wrap">
    <table className="legal-table">
      <thead><tr>{Object.keys(rows[0]).map(k => <th key={k}>{k}</th>)}</tr></thead>
      <tbody>{rows.map((row, i) => <tr key={i}>{Object.values(row).map((v, j) => <td key={j}>{v}</td>)}</tr>)}</tbody>
    </table>
  </div>
);

const sections = [
  {
    id: 'acceptance',
    label: '1. Acceptance',
    title: '1. Acceptance of Terms',
    content: (
      <>
        <P>These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Peptide AI LLC, a limited liability company ("PeptideAI," "Company," "we," "us," or "our"), governing your access to and use of the PeptideAI platform, website, mobile application, application programming interfaces, content, tools, and all related services (collectively, the "Platform" or "Service").</P>
        <P>By creating an account, accessing any content, submitting any data, or using any feature of the Platform, you represent and warrant that: (a) you are at least 18 years of age; (b) you have the legal capacity to enter into a binding contract; (c) you are not prohibited from accessing or using the Platform under applicable law; and (d) you have read, understood, and agree to be bound by these Terms and our Privacy Policy, which is incorporated herein by reference.</P>
        <Warn>IF YOU ARE USING THE PLATFORM ON BEHALF OF AN ORGANIZATION, YOU REPRESENT AND WARRANT THAT YOU HAVE THE AUTHORITY TO BIND THAT ORGANIZATION TO THESE TERMS, AND ALL REFERENCES TO "YOU" SHALL REFER TO THAT ORGANIZATION.</Warn>
      </>
    ),
  },
  {
    id: 'definitions',
    label: '2. Definitions',
    title: '2. Definitions',
    content: (
      <Table rows={[
        { Term: '"Platform"', Meaning: 'The PeptideAI website, mobile application, API, content library, AI consulting tools, and all associated features and services.' },
        { Term: '"Content"', Meaning: 'All text, data, information, educational materials, AI-generated outputs, research summaries, and other materials available through the Platform.' },
        { Term: '"User Data"', Meaning: 'Any data, information, content, or materials you submit, upload, transmit, or otherwise provide to the Platform, including consulting queries and personal information.' },
        { Term: '"AI Output"', Meaning: "Any response, interpretation, analysis, recommendation, summary, or other output generated by PeptideAI's artificial intelligence systems." },
        { Term: '"Subscription"', Meaning: 'A paid plan granting access to certain Platform features for a defined period.' },
      ]} />
    ),
  },
  {
    id: 'purpose',
    label: '3. Purpose & Limitations',
    title: '3. Platform Purpose and Limitations',
    content: (
      <>
        <Warn>THIS PLATFORM IS FOR EDUCATIONAL AND CONSULTING PURPOSES ONLY. PeptideAI is a SaaS peptide consulting and educational platform powered by artificial intelligence. Nothing on the Platform constitutes, or should be construed as, medical advice, clinical guidance, a diagnosis, a treatment plan, or a prescription. The Platform is not a medical device, telehealth service, or healthcare provider.</Warn>
        <P><strong>3.1 Educational and Consulting Purpose.</strong> PeptideAI provides AI-powered consulting and educational information about peptides and related compounds. All information, AI outputs, and content provided through the Platform are for general informational, educational, and consulting purposes only.</P>
        <P><strong>3.2 No Medical Advice.</strong> The Platform does not provide medical advice. AI-generated outputs, content, and all other information provided through the Platform are not a substitute for professional medical advice, diagnosis, or treatment from a qualified, licensed healthcare provider who knows your individual medical history.</P>
        <P><strong>3.3 Always Seek Professional Guidance.</strong> You should always seek the advice of your physician, pharmacist, or other qualified healthcare professional before making any decisions about your health. Never disregard professional medical advice or delay seeking it because of something you have read, viewed, or received from PeptideAI.</P>
        <P><strong>3.4 Emergency Situations.</strong> PeptideAI is not designed for emergency medical situations. If you believe you are experiencing a medical emergency, call 911 or your local emergency services immediately.</P>
        <P><strong>3.5 Jurisdiction and Legality.</strong> Laws governing peptides and related compounds vary by jurisdiction. It is your sole responsibility to understand and comply with all applicable local, state, federal, and international laws. PeptideAI makes no representation that any substance discussed is legal in your jurisdiction.</P>
      </>
    ),
  },
  {
    id: 'account',
    label: '4. Account Registration',
    title: '4. Account Registration and Eligibility',
    content: (
      <>
        <P><strong>4.1 Age Requirement.</strong> You must be at least 18 years of age to create an account or use the Platform. By registering, you represent and warrant that you meet this age requirement.</P>
        <P><strong>4.2 Account Accuracy.</strong> You agree to provide accurate, current, and complete information during registration and to keep your account information updated. You are responsible for all activity that occurs under your account.</P>
        <P><strong>4.3 Account Security.</strong> You are solely responsible for maintaining the confidentiality of your account credentials. You agree to notify PeptideAI immediately of any unauthorized use of your account. PeptideAI is not liable for any loss resulting from unauthorized use of your credentials.</P>
        <P><strong>4.4 Prohibited Users.</strong> You may not create an account or use the Platform if: (a) you have been previously suspended or terminated from the Platform; (b) you are located in a jurisdiction where use of the Platform is prohibited by law; or (c) you are under 18 years of age.</P>
      </>
    ),
  },
  {
    id: 'conduct',
    label: '5. Permitted Use',
    title: '5. Permitted Use and Prohibited Conduct',
    content: (
      <>
        <p className="legal-p"><strong>5.1 Permitted Uses</strong></p>
        <UL items={[
          'Accessing and reviewing educational and consulting content for personal or professional study;',
          'Using the AI consulting tools to research peptide-related topics and access educational information;',
          'Submitting queries to receive AI-generated educational context and consulting insights;',
          'Participating in community features in accordance with our Community Guidelines;',
          'Using the Platform for legitimate research, academic, or professional purposes.',
        ]} />
        <p className="legal-p" style={{ marginTop: '1.25rem' }}><strong>5.2 Prohibited Conduct — You expressly agree NOT to:</strong></p>
        <UL items={[
          'Rely on AI Output as a substitute for professional medical, legal, pharmaceutical, or financial advice;',
          'Use the Platform to facilitate the illegal purchase, sale, distribution, or importation of any substance;',
          "Misrepresent the nature of any substance or PeptideAI's services to any third party;",
          'Attempt to reverse engineer, scrape, crawl, or extract data from the Platform by automated means without express written permission;',
          'Upload false, misleading, or fraudulent data;',
          'Use the Platform for any unlawful purpose or in violation of any applicable laws or regulations;',
          'Harass, threaten, or harm other users;',
          'Impersonate any person or entity or misrepresent your affiliation with any person or entity;',
          'Circumvent any access controls, security measures, or usage limits of the Platform;',
          'Use the Platform if you are a minor or are accessing on behalf of a minor.',
        ]} />
      </>
    ),
  },
  {
    id: 'subscriptions',
    label: '6. Subscriptions & Payments',
    title: '6. Subscriptions, Payments, and Refunds',
    content: (
      <>
        <P><strong>6.1 Subscription Plans.</strong> PeptideAI offers various subscription tiers as described on the Platform. Subscription fees are billed in advance on a monthly or annual basis. All fees are in U.S. dollars unless otherwise stated.</P>
        <P><strong>6.2 Automatic Renewal.</strong> Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date. By subscribing, you authorize PeptideAI to charge your payment method automatically upon renewal.</P>
        <P><strong>6.3 Cancellation.</strong> You may cancel your subscription at any time through your account settings or by contacting us. Cancellation takes effect at the end of the current billing period. You will retain access to paid features until that date.</P>
        <P><strong>6.4 Refunds.</strong> All subscription fees are non-refundable except as required by applicable law or as expressly stated in our refund policy. PeptideAI reserves the right to issue refunds at its sole discretion on a case-by-case basis.</P>
        <P><strong>6.5 Price Changes.</strong> PeptideAI reserves the right to modify subscription pricing at any time. We will provide at least 30 days' notice of any price increase. Continued use after the effective date of a price change constitutes your acceptance of the new pricing.</P>
        <P><strong>6.6 Taxes.</strong> You are responsible for all applicable taxes arising from your use of the Platform and your purchase of any subscriptions or products.</P>
      </>
    ),
  },
  {
    id: 'ip',
    label: '7. Intellectual Property',
    title: '7. Intellectual Property Rights',
    content: (
      <>
        <P><strong>7.1 PeptideAI Ownership.</strong> The Platform and all of its content, features, functionality, design, code, trademarks, logos, and trade names — including but not limited to the PeptideAI name, the peptide education library, AI systems, and all associated intellectual property — are owned by Peptide AI LLC or its licensors and are protected by U.S. and international intellectual property laws.</P>
        <P><strong>7.2 Limited License to Users.</strong> Subject to your compliance with these Terms, PeptideAI grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Platform for personal, non-commercial research, educational, and consulting purposes only.</P>
        <P><strong>7.3 Restrictions.</strong> You may not copy, reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, transmit, sell, or sublicense any portion of the Platform or its content without PeptideAI's prior written consent.</P>
        <P><strong>7.4 User-Submitted Content.</strong> By submitting any data, content, or materials to the Platform, you grant PeptideAI a worldwide, royalty-free, irrevocable, perpetual, sublicensable license to use, reproduce, process, adapt, modify, publish, transmit, display, and distribute such content for any purpose, including commercial purposes, in connection with the operation of the Platform and as further described in our Privacy Policy.</P>
        <P><strong>7.5 Feedback.</strong> Any feedback, suggestions, or ideas you provide to PeptideAI regarding the Platform may be used by PeptideAI freely without any obligation to you.</P>
      </>
    ),
  },
  {
    id: 'warranties',
    label: '8. Disclaimer of Warranties',
    title: '8. Disclaimer of Warranties',
    content: (
      <>
        <Warn>THE PLATFORM, ALL CONTENT, AI OUTPUT, AND ALL SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, PEPTIDEAI EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE.</Warn>
        <P>Without limiting the foregoing, PeptideAI specifically disclaims all warranties, including but not limited to:</P>
        <UL items={[
          'Any implied warranty of merchantability, fitness for a particular purpose, title, or non-infringement;',
          'That the Platform will meet your requirements or be available on an uninterrupted, secure, or error-free basis;',
          'That AI Output will be accurate, complete, current, reliable, or suitable for any purpose;',
          'That the Platform is free of viruses, malware, or other harmful components;',
          'That use of the Platform will result in any particular research, consulting, or educational outcome.',
        ]} />
      </>
    ),
  },
  {
    id: 'liability',
    label: '9. Limitation of Liability',
    title: '9. Limitation of Liability',
    content: (
      <>
        <Warn>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PEPTIDEAI LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, MEMBERS, AGENTS, CONTRACTORS, LICENSORS, PARTNERS, OR AFFILIATES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES WHATSOEVER.</Warn>
        <P><strong>9.1 Scope of Limitation.</strong> This limitation of liability applies to all claims arising out of or related to your use of the Platform, regardless of the legal theory asserted, including but not limited to: contract, tort (including negligence), strict liability, misrepresentation, or any other legal or equitable theory.</P>
        <P><strong>9.2 Specific Exclusions.</strong> Without limiting the foregoing, PeptideAI shall not be liable for:</P>
        <UL items={[
          'Any damages arising from your reliance on AI Output, educational content, or any other information provided through the Platform;',
          'Any loss of data, profit, revenue, business, goodwill, or opportunity;',
          'Any unauthorized access to your account or User Data;',
          'Any errors, inaccuracies, or omissions in AI Output or Platform content;',
          'Any interruption or unavailability of the Platform;',
          'Any conduct or content of third parties on or through the Platform.',
        ]} />
        <P><strong>9.3 Cap on Liability.</strong> To the extent PeptideAI is found liable for any claim, PeptideAI's total cumulative liability to you for all claims arising out of or relating to these Terms or the Platform shall not exceed the greater of: (a) the total amount you paid to PeptideAI in the twelve (12) months immediately preceding the claim; or (b) one hundred U.S. dollars ($100.00).</P>
      </>
    ),
  },
  {
    id: 'indemnification',
    label: '10. Indemnification',
    title: '10. Indemnification',
    content: (
      <P>You agree to defend, indemnify, and hold harmless Peptide AI LLC and its officers, directors, members, employees, agents, contractors, partners, licensors, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) your use of or access to the Platform; (b) your violation of these Terms; (c) your violation of any applicable law, regulation, or third-party right; (d) your reliance on any Platform content or AI Output; (e) any User Data you submit to the Platform; or (f) any claim that your User Data infringes the rights of a third party.</P>
    ),
  },
  {
    id: 'disputes',
    label: '11. Governing Law & Disputes',
    title: '11. Governing Law, Dispute Resolution, and Arbitration',
    content: (
      <>
        <P><strong>11.1 Governing Law.</strong> These Terms shall be governed by and construed in accordance with the laws of the State of Virginia, without regard to its conflict of laws provisions.</P>
        <P><strong>11.2 Binding Arbitration.</strong> EXCEPT FOR DISPUTES THAT QUALIFY FOR SMALL CLAIMS COURT, ALL DISPUTES, CLAIMS, AND CONTROVERSIES ARISING OUT OF OR RELATING TO THESE TERMS OR THE PLATFORM SHALL BE RESOLVED BY BINDING INDIVIDUAL ARBITRATION rather than in court. The arbitration shall be conducted by a recognized arbitration provider under its applicable rules. The arbitrator's decision shall be final and binding and may be entered as a judgment in any court of competent jurisdiction.</P>
        <P><strong>11.3 Class Action Waiver.</strong> YOU AGREE THAT ANY CLAIMS AGAINST PEPTIDEAI SHALL BE BROUGHT SOLELY IN YOUR INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS, COLLECTIVE, REPRESENTATIVE, OR PRIVATE ATTORNEY GENERAL ACTION.</P>
        <P><strong>11.4 Jury Trial Waiver.</strong> TO THE EXTENT ARBITRATION DOES NOT APPLY, YOU AND PEPTIDEAI EACH WAIVE ANY RIGHT TO A JURY TRIAL IN ANY COURT PROCEEDING.</P>
        <P><strong>11.5 Time Limitation.</strong> Any claim arising out of these Terms or the Platform must be brought within one (1) year of the date the cause of action arose, or it is permanently waived and barred.</P>
      </>
    ),
  },
  {
    id: 'termination',
    label: '12. Termination',
    title: '12. Termination and Suspension',
    content: (
      <>
        <P><strong>12.1 PeptideAI's Right to Terminate.</strong> PeptideAI reserves the right to suspend or terminate your access to the Platform at any time, with or without notice, for any reason, including but not limited to: (a) breach of these Terms; (b) conduct that PeptideAI believes harms the Platform, other users, or PeptideAI; (c) failure to pay applicable fees; or (d) any conduct that violates applicable law.</P>
        <P><strong>12.2 Your Right to Terminate.</strong> You may terminate your account at any time by contacting us or through your account settings. Termination does not entitle you to any refund of fees paid.</P>
        <P><strong>12.3 Effect of Termination.</strong> Upon termination, your right to use the Platform ceases immediately. Provisions of these Terms that by their nature should survive termination shall survive, including but not limited to: Disclaimer of Warranties, Limitation of Liability, Indemnification, Governing Law, and any licenses granted by you to PeptideAI with respect to User Data.</P>
        <P><strong>12.4 Data Following Termination.</strong> Following account termination, PeptideAI may retain your User Data as described in the Privacy Policy and as permitted by applicable law. Anonymized and aggregated data derived from your use of the Platform may be retained indefinitely.</P>
      </>
    ),
  },
  {
    id: 'modifications',
    label: '13. Modifications',
    title: '13. Modifications to Terms and Platform',
    content: (
      <>
        <P>PeptideAI reserves the right to modify these Terms at any time in its sole discretion. We will notify you of material changes by posting the updated Terms on the Platform and updating the "Last Updated" date. For significant changes, we may provide additional notice via email. Your continued use of the Platform after the effective date of any modification constitutes your acceptance of the updated Terms.</P>
        <P>PeptideAI also reserves the right to modify, suspend, or discontinue the Platform or any features thereof at any time without notice or liability.</P>
      </>
    ),
  },
  {
    id: 'general',
    label: '14. General Provisions',
    title: '14. General Provisions',
    content: (
      <>
        <P><strong>14.1 Entire Agreement.</strong> These Terms, together with the Privacy Policy and any additional terms applicable to specific features or services, constitute the entire agreement between you and PeptideAI regarding the Platform and supersede all prior agreements and understandings.</P>
        <P><strong>14.2 Severability.</strong> If any provision of these Terms is found to be unenforceable, that provision shall be modified to the minimum extent necessary to make it enforceable, and the remainder of the Terms shall continue in full force and effect.</P>
        <P><strong>14.3 Waiver.</strong> No failure by PeptideAI to enforce any right or provision of these Terms shall constitute a waiver of that right or provision.</P>
        <P><strong>14.4 Assignment.</strong> You may not assign or transfer your rights or obligations under these Terms without PeptideAI's prior written consent. PeptideAI may freely assign these Terms in connection with a merger, acquisition, reorganization, or sale of assets.</P>
        <P><strong>14.5 Contact.</strong> Questions about these Terms should be directed to: <a className="legal-link" href="mailto:legal@peptideai.co">legal@peptideai.co</a></P>
      </>
    ),
  },
];

export default function TermsOfService() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle="Please read these terms carefully before using the Platform."
      effectiveDate="March 8, 2026"
      sections={sections}
    />
  );
}
